apiVersion: v1
kind: Namespace
metadata:
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
spec:
  finalizers:
  - kubernetes
