## Si no existe un operatorgroup en el ns lo creo, si existe no hago nada
{{- $exists := lookup "operators.coreos.com/v1" "OperatorGroup" .Values.namespace "" }}
{{- if (eq (len $exists.items)  0 ) }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operatorgroup }}
  namespace: {{ .Values.namespace }}
spec:
  targetNamespaces:
    -  {{ .Values.namespace }}
  upgradeStrategy: Default
{{- end }}
