{{- $varog := lookup "operators.coreos.com/v1" "OperatorGroup" .Values.namespace "" }}
{{- if $varog.items | len | gt 0 }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.operatorgroup }}
spec:
  targetNamespaces:
    -  {{ .Values.namespace }}
  upgradeStrategy: Default
{{- end }}
