apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-subscriptions
rules:
- apiGroups: ["operators.coreos.com"]
  resources: ["subscriptions"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["operators.coreos.com"]
  resources: ["installplans"]
  verbs: ["get", "list", "watch", "patch"]
