apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-subscriptions-binding
subjects:
- kind: ServiceAccount
  name: oper-helper
roleRef:
  kind: Role
  name: read-subscriptions
  apiGroup: rbac.authorization.k8s.io