apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.operator }}
  namespace: {{ .Values.namespace }}
#  annotations:
#    argocd.argoproj.io/ignore-differences: |
#      jsonPointers:
#        - /spec/installPlanApproval
#        - /status  
spec:
  channel: {{ .Values.channel }}
  installPlanApproval: Manual
  name:  {{ .Values.operator }}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
# Para instalar un version en particular, sino instalara la mas reciente  
#  startingCSV: jws-operator.v2.0.11

