apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.operator }}
spec:
  channel: alpha
  installPlanApproval: Manual
  name:  {{ .Values.operator }}
  source: redhat-operators
  sourceNamespace: openshift-marketplace

