apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jws-operator
spec:
  channel: alpha
  installPlanApproval: Manual
  name: jws-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace

