# Default values for oper-installer.

namespace: redhat-pruebas
operator: jws-operator


image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
