# Default values for oper-installer.
# Para setear automaticamente el manejo del namespace por ArgoCD
# es necesario que el project de argo tenga a kind namespace en CLUSTER RESOURCE ALLOW LIST 


# donde se instala el operador
namespace: app-sso-service
# donde se instalan los recursos creados por el operador, generalmente igual a namespace
targetnamespace: app-sso-service

# operador a instalar, debe ser el nombre exacto
operator: rhsso-operator
channel: stable

# Depende del operador, esto es donde se graba el objeto OG correspondiente al operador a 
# instalar, muchos operadores comparten el OG
operatornamespace: app-sso-service 
# name del OG, puede ser fantasia, pero si existe debe coincidir
operatorgroup: operator-group


