# Default values for oper-installer.
# Para setear automaticamente el manejo del namespace por ArgoCD
# es necesario que el project de argo tenga a kind namespace en CLUSTER RESOURCE ALLOW LIST 
#DONE

# donde se instala el operador
namespace: openshift-distributed-tracing
# donde se instalan los recursos creados por el operador, generalmente igual a namespace
targetnamespace: openshift-distributed-tracing
# define si se incluye el tag targetnamespace en el operatorgroup, segun el tipo de operador
includeTargetNS: false

# operador a instalar, debe ser el nombre exacto
operator: jaeger-product
channel: stable

# Depende del operador, esto es donde se graba el objeto OG correspondiente al operador a 
# instalar, muchos operadores comparten el OG
operatornamespace: openshift-distributed-tracing 
# name del OG, puede ser fantasia
operatorgroup: openshift-distributed-tracing


